CREATE TABLE IF NOT EXISTS users (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	email varchar NOT NULL UNIQUE,
	name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS categories (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS locations (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	lat varchar NOT NULL,
	lon varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS states (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	state_description varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS events (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	annotation varchar NOT NULL,
	category INTEGER REFERENCES categories (id) ON DELETE CASCADE,
	created_on TIMESTAMP,
	description varchar NOT NULL,
	event_date TIMESTAMP,
	initiator BIGINT REFERENCES users (id) ON DELETE CASCADE,
	location BIGINT REFERENCES locations (id) ON DELETE CASCADE,
	paid BOOLEAN NOT NULL,
	participants_limit BIGINT,
	published_on timestamp,
	request_moderation BOOLEAN NOT NULL,
	state varchar, --INTEGER REFERENCES states (id) ON DELETE CASCADE,
	title varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS status (
	id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	status_description varchar NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS requests (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	created TIMESTAMP NOT NULL,
	event BIGINT REFERENCES events (id),
	requester BIGINT REFERENCES users (id),
	status varchar --INTEGER REFERENCES status (id)
);
